### ISSUE TITLE
GetAllAccountsAsync not Work (request timestamp expired)

### ISSUE THREAD

**Issue by linpiero** [dougdellolio/gdax-csharp#40] opened 2018-01-05 16:24 UTC
Hi,
if I call GetAllAccountsAsync i have the error : "System.Net.Http.HttpRequestException: '{"message":"request timestamp expired"}'
"

**Comment by dougdellolio** [comment] 2018-01-06 00:19
Hi,

It is hard to say what the problem is here. Please ensure that you are providing correct API key and secret. If still nothing, please provide code (excluding your api keys and other personal info)

thanks!

**Comment by cquinterox** [comment] 2018-01-06 05:55
It works for me. I had this issue when trying out a Python client because I held the request in debug for too long which caused the server to reject my (now stale) time stamp.

**Comment by alexandredubois** [comment] 2018-01-06 17:56
Hi,
Same here, HTTP 400 : {"message":"invalid timestamp"}
Capturing the HTTP request with Fiddler, i see the CB-ACCESS-TIMESTAMP header with a decimal value: is-it normal ?

CB-ACCESS-TIMESTAMP: 1515261195,2098

I'll try investigating further,

Alex

**Comment by dougdellolio** [comment] 2018-01-06 18:03
@alexandredubois i believe that could be a different issue. make sure you are using the latest code as this was a problem in previous versions due to cultureinfo. the fix for it went in here: (https://github.com/dougdellolio/gdax-csharp/pull/32).

the timestamp should be a decimal, yes

**Comment by alexandredubois** [comment] 2018-01-06 18:56
I fixed the problem locally (pull request coming).
I guess the problem is with the format. Removing the decimal part, everything is working on my side.

**Comment by dougdellolio** [comment] 2018-01-06 20:43
hm interesting. feel free to open a PR.

**Comment by linpiero** [comment] 2018-01-06 21:04
the problem is the time of the pc, is it possible to pass  "the timestamp" as a parameter in every service (calling the api https://docs.gdax.com/#time)?

**Comment by dougdellolio** [comment] 2018-01-06 21:12
we could do that but I feel like the user should not have to worry about passing in the time, the library should take care of it for you 

@alexandredubois has a PR open now that seems to fix it if you want to try it out and see if it fixes your issue. https://github.com/dougdellolio/gdax-csharp/pull/42

**Comment by linpiero** [comment] 2018-01-08 08:04
boolean parameter? if true the library use the time from (https://docs.gdax.com/#time), if false use localtime.can it be a solution?

**Comment by dougdellolio** [comment] 2018-01-08 20:25
The time issue should be fixed with the latest version from PR #42 so I don’t think we would need to pass in time or read from the GDAX api

Let me know if it is still an issue.

**Comment by linpiero** [comment] 2018-01-09 08:08
I have updated to the latest version, but the problem is not solved if the pc time is not synchronized with the gdax time.
https://docs.gdax.com/#selecting-a-timestamp

**Comment by dougdellolio** [comment] 2018-01-09 15:56
Sorry to hear it’s still not working. The time doesn’t have to match that endpoint exactly. The api states it can be within 30 seconds with anything after considered expired. 

Might be best to provide some code here (omitting your keys) to help debug the issue as I believe the problem lies with how the api is being called

**Comment by linpiero** [comment] 2018-01-09 16:03
the code works perfectly !!!. I repeat, the problem is my PC which has the local time not synchronized for 2 minutes and I can not modify it.
That's why I asked you to use the Boolean parameter or the ability to pass the timestamp.
Thanks for your patience

**Comment by dougdellolio** [comment] 2018-01-09 17:15
okay no problem. Feel free to open a PR with this change 

Thanks

**Closed by dougdellolio** 2018-01-09 17:15 UTC
